FROM ubuntu:20.04

WORKDIR /in_container 

RUN apt update
RUN apt-get install -y build-essential

#for python
#RUN apt update
#RUN apt-get install -y  software-properties-common
#RUN add-apt-repository ppa:deadsnakes/ppa
RUN apt-get install -y python3-pip


#for java
#RUN apt-get install -y default-jre
#RUN apt-get install -y default-jdk

